### ISSUE TITLE
Error to  load elasticsearch.cluster.nodes.processors graph report

### ISSUE THREAD

**Issue by indigo423** [opennms-config-modules/elasticsearch#1]
The following error message is shown when graph report is requested:
```
alog&start=1485137137262&end=1485185521262&] o.o.n.d.s.PropertiesGraphDao: Failed to load report 'elasticsearch.cluster.nodes.processors'
org.springframework.dao.DataAccessResourceFailureException: Properties for report 'elasticsearch.cluster.nodes.processors' must contain 'report.elasticsearch.cluster.nodes.processors.name' property
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.getReportProperty(PropertiesGraphDao.java:645) ~[opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.makePrefabGraph(PropertiesGraphDao.java:554) ~[opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.loadPrefabGraphDefinitions(PropertiesGraphDao.java:532) [opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.loadIncludedFile(PropertiesGraphDao.java:220) [opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.scanIncludeDirectory(PropertiesGraphDao.java:284) [opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.rescanIncludeDirectory(PropertiesGraphDao.java:199) [opennms-dao-18.0.3.jar:?]
        at org.opennms.netmgt.dao.support.PropertiesGraphDao.getPrefabGraph(PropertiesGraphDao.java:750) [opennms-dao-18.0.3.jar:?]
        at org.opennms.web.svclayer.support.DefaultGraphResultsService.createGraphResultSet(DefaultGraphResultsService.java:215) [opennms-web-api-18.0.3.jar:?]
        at org.opennms.web.svclayer.support.DefaultGraphResultsService.findResults(DefaultGraphResultsService.java:141) [opennms-web-api-18.0.3.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [org.apache.servicemix.bundles.spring-aop-4.0.5.RELEASE_1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [org.apache.servicemix.bundles.spring-aop-4.0.5.RELEASE_1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [org.apache.servicemix.bundles.spring-aop-4.0.5.RELEASE_1.jar:?]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) [org.apache.servicemix.bundles.spring-tx-4.0.5.RELEASE_1.jar:?]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) [org.apache.servicemix.bundles.spring-tx-4.0.5.RELEASE_1.jar:?]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) [org.apache.servicemix.bundles.spring-tx-4.0.5.RELEASE_1.jar:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [org.apache.servicemix.bundles.spring-aop-4.0.5.RELEASE_1.jar:?]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [org.apache.servicemix.bundles.spring-aop-4.0.5.RELEASE_1.jar:?]
        at com.sun.proxy.$Proxy179.findResults(Unknown Source) [?:?]
```

The Elasticsearch Node processor graph report is not shown.

**Comment by indigo423** [comment]
Resolved with 94625c695344c0e0c64c74d44132fa846f282e31
